md "Todos os Paises"
cd "Todos os Paises"
md "Argentina" "Bolivia" "Brasil" "Chile" "Colombia" "Equador" "Guiana" 
md "Guiana Francesa" "Paraguai" "Peru" "Suriname" "Uruguai" "Venezuela"  
cd Brasil
md "Acre" "Alagoas" "Amapa" "Amazonas" "Bahia" 
md "Ceara" "Espirito Santo" "Goias" "Maranhao" "Mato Grosso" "Mato Grosso do Sul"
md "Minas Gerais" "Para" "Paraiba" "Parana" "Pernambuco"
md "Piaui" "Rio de Janeiro" "Rio Grande do Norte" "Rio Grande do Sul" "Rondonia"        
md "Roraima" "Santa Catarina" "Sao Paulo" "Sergipe" "Tocantins"  
