md "Todos os clubes"
cd "Todos os clubes"
md "Serie A" "Serie B"
cd "Serie A"
md "America-MG" "Athetico-PR" "Atletico-GO" "Atletico-MG" "Bahia"
md "Bragantino" "Ceara" "Chapecoense" "Corinthians" "Cuiaba" 
md "Flamengo" "Fluminense" "Fortaleza" "Gremio" "Internacional" 
md "Juventude" "Palmeiras" "Santos" "Sao Paulo" "Sport"         
cd..
cd "Serie B"
md "Avai" "Botafogo" "Brasil de Pelotas" "Brusque" "CBR"     
md "Confianca" "Coritiba" "Cruzeiro" "CSA" "Goias"     
md "Guarani" "Londrina" "Nautico" "Operario-PR" "Ponte Preta"     
md "Remo" "Sampaio Correa" "Vasco" "Vila Nova" "Vitoria"   