md "Todos os clubes"
cd "Todos os clubes"
md "Serie A" "Serie B"
cd "Serie A"
md "Atletico-MG" "Palmeiras" "Fortaleza" "Bragantino" "Flamengo" "Athetico-PR" "Atletico-GO" "Ceara" "Internacional" "Santos"
md "Corinthians" "Juventude" "Bahia" "Sao Paulo" "Fluminense" "Cuiaba" "Sport" "America-MG" "Gremio" "Chapecoense"